# Generated by Django 5.0.2 on 2024-02-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.CharField(choices=[('TSU', 'Tecnico superior universitario'), ('Ing', 'Ingenieria'), ('Lic', 'Licenciatura'), ('M', 'Maestria')], max_length=20, verbose_name='Nivel'),
        ),
    ]
